package com.github.tommyettinger;

/**
 * Created by Tommy Ettinger on 3/10/2015.
 */
public enum TilesetType
{
    DEFAULT_DUNGEON,
    CAVES_LIMIT_CONNECTIVITY,
    CAVES_TINY_CORRIDORS,
    CORNER_CAVES,
    HORIZONTAL_CORRIDORS_A,
    HORIZONTAL_CORRIDORS_B,
    HORIZONTAL_CORRIDORS_C,
    LIMIT_CONNECTIVITY_FAT,
    LIMITED_CONNECTIVITY,
    MAZE_A,
    MAZE_B,
    OPEN_AREAS,
    REFERENCE_CAVES,
    ROOMS_AND_CORRIDORS_A,
    ROOMS_AND_CORRIDORS_B,
    ROOMS_LIMIT_CONNECTIVITY,
    ROUND_ROOMS_DIAGONAL_CORRIDORS,
    SIMPLE_CAVES,
    SQUARE_ROOMS_WITH_RANDOM_RECTS
}

